import { TCarouselItem } from '@/types';

export const carouselTop: TCarouselItem[] = [
  {
    id: 1,
    title: 'Jolene',
    description: "Calathea 'Elgergrass'",
    price: 28,
    isOptions: false,
    img: '/pictures/rb1llk8t58q7sdid5jvj.webp',
  },
  {
    id: 2,
    title: 'Clay pot',
    price: 5,
    isOptions: true,
    img: '/pictures/gdiqpkze6rhc2jrvgnjd.webp',
  },
  {
    id: 3,
    description: 'Peace Lily',
    title: 'Pippa',
    price: 10,
    isOptions: true,
    img: '/pictures/cjbnqexhcuzi0vytagx5.webp',
  },
  {
    id: 4,
    description: "Ctenanthe 'Compactstar'",
    title: 'Jo',
    price: 28,
    isOptions: false,
    img: '/pictures/w2lwtamj04ppunsffus2.webp',
  },
  {
    id: 5,
    description: 'Snake plant',
    title: 'Susie',
    price: 10,
    isOptions: true,
    img: '/pictures/snake-plant-dda326.webp',
  },
  {
    id: 6,
    title: 'Fractured pot',
    price: 16,
    isOptions: true,
    img: '/pictures/xrmx5sdmsccqsz02ny2l.webp',
  },
  {
    id: 7,
    description: "Devil's ivy",
    title: 'Rapunzel',
    price: 15,
    isOptions: true,
    img: '/pictures/ypgmev3z0gfcl1ucxmhb.webp',
  },
  {
    id: 8,
    title: 'Ceramic glazed pot',
    price: 5,
    isOptions: true,
    img: '/pictures/fhtfccbsdillkd6dtbqy.webp',
  },
  {
    id: 9,
    description: 'Satin Pothos',
    title: 'Silvy',
    price: 16,
    isOptions: true,
    img: '/pictures/mwawyu5we0cx7mfozvxn.jpg',
  },
  {
    id: 10,
    description: 'Boston Fern',
    title: 'Bertie',
    price: 4,
    isOptions: true,
    img: '/pictures/boston-fern-42361f.webp',
  },
];

export const carouselBottom: TCarouselItem[] = [
  {
    id: 1,
    description: '120-130cm',
    title: 'Big Ken',
    price: 75,
    isOptions: false,
    img: '/pictures/vxnuidely9mqnh1zuwuv.webp',
  },
  {
    id: 2,
    description: '30-4-cm',
    title: 'Lizzie',
    price: 18,
    isOptions: false,
    img: '/pictures/c0ks5bx9bqhkrd2uypje.webp',
  },
  {
    id: 3,
    description: '60-70cm',
    title: 'Vivi',
    price: 55,
    isOptions: false,
    img: '/pictures/mfmn4ta9wdrh6uqxdojf.webp',
  },
  {
    id: 4,
    description: '30-40cm',
    title: 'Rachel',
    price: 22,
    isOptions: false,
    img: '/pictures/tq9rqwf7ygadun8gpdfm.webp',
  },
  {
    id: 5,
    description: 'Pots included',
    title: 'Propagation set',
    price: 100,
    isOptions: false,
    img: '/pictures/ozclyqtmkee4uiqxkbm5.webp',
  },
  {
    id: 6,
    description: '30-40cm',
    title: 'Lorenzo',
    price: 18,
    isOptions: false,
    img: '/pictures/h14r0wmq1dwq9pd9rpwa.webp',
  },
  {
    id: 7,
    description: '15.5 - blue',
    title: 'Fractured pot',
    price: 20,
    isOptions: false,
    img: '/pictures/jrb2tin7dj9qyjcemnoj.webp',
  },
  {
    id: 8,
    description: '50-60cm',
    title: 'Susie',
    price: 20,
    isOptions: false,
    img: '/pictures/him4opgqrfnizgnrzrgi.webp',
  },
  {
    id: 9,
    description: '70-80cm',
    title: 'Sharon',
    price: 36,
    isOptions: false,
    img: '/pictures/ih9xyrjlx3wwozvj2vai.webp',
  },
  {
    id: 10,
    description: '20-30cm',
    title: 'Hugh',
    price: 12,
    isOptions: false,
    img: '/pictures/prvaesk5zv1amaqdfcqn.webp',
  },
  {
    id: 11,
    description: '25cm - pink',
    title: 'Dipped pot in stand',
    price: 100,
    isOptions: false,
    img: '/pictures/noovqiilppwn6v3iyfbt.webp',
  },
  {
    id: 12,
    description: '120-130cm',
    title: 'Laura tree',
    price: 75,
    isOptions: false,
    img: '/pictures/fdsuax2tgzhqad9wesmf.jpg',
  },
  {
    id: 13,
    description: '10-20cm',
    title: 'Suri',
    price: 8,
    isOptions: false,
    img: '/pictures/bjhxooj9qq7mvhzk368c.webp',
  },
  {
    id: 14,
    title: 'Secateurs',
    price: 18,
    isOptions: false,
    img: '/pictures/ox3cn4sjtfxnnn2jgpek.webp',
  },
  {
    id: 15,
    description: 'Pots included',
    title: 'Unkillable set',
    price: 180,
    isOptions: false,
    img: '/pictures/uyqprhxwdxligxwedzlo.webp',
  },
  {
    id: 16,
    description: '13cm',
    title: 'Clay pot',
    price: 12,
    isOptions: false,
    img: '/pictures/blybad1kjiwgs3fmsfoe.webp',
  },
  {
    id: 17,
    description: '50-60cm',
    title: 'Piña',
    price: 25,
    isOptions: false,
    img: '/pictures/oxjeobm3sjmz1xxeudyo.webp',
  },
  {
    id: 18,
    description: '90-100cm',
    title: 'Ivy',
    price: 25,
    isOptions: false,
    img: '/pictures/xpfb2inkgcuscuoq8fia.jpg',
  },
];
