export const filtersArray = [
  {
    title: 'Light',
    filters: [
      {
        id: 'id_light_0',
        name: 'light',
        value: 'direct-sunlight',
        label: 'Happiest in direct sunlight',
        count: 62,
      },
      {
        id: 'id_light_1',
        name: 'light',
        value: 'light-shade',
        label: 'Happy in light and shade',
        count: 87,
      },
      {
        id: 'id_light_2',
        name: 'light',
        value: 'shade',
        label: 'Happy in shade',
        count: 27,
      },
    ],
  },
  {
    title: 'Care level',
    filters: [
      {
        id: 'id_care-level_0',
        name: 'care-level',
        value: 'easy-to-care-for',
        label: 'Easy to care for',
        count: 101,
      },
      {
        id: 'id_care-level_1',
        name: 'care-level',
        value: 'un-killable',
        label: 'Almost un-killable',
        count: 35,
      },
      {
        id: 'id_care-level_2',
        name: 'care-level',
        value: 'needs-some-love',
        label: 'Needs some love',
        count: 16,
      },
    ],
  },
  {
    title: 'Wind',
    filters: [
      {
        id: 'id_wind-requirements_0',
        name: 'wind-requirements',
        value: 'lots',
        label: 'Can handle wind',
        count: 35,
      },
      {
        id: 'id_wind-requirements_1',
        name: 'wind-requirements',
        value: 'none',
        label: "Can't handle wind",
        count: 95,
      },
    ],
  },
  {
    title: 'Special feature',
    filters: [
      {
        id: 'id_special-feature_0',
        name: 'special-feature',
        value: 'flowering',
        label: 'Flowering',
        count: 23,
      },
      {
        id: 'id_special-feature_1',
        name: 'special-feature',
        value: 'pollinator-friendly',
        label: 'Pollinator friendly',
        count: 10,
      },
      {
        id: 'id_special-feature_3',
        name: 'special-feature',
        value: 'evergreen',
        label: 'Evergreen',
        count: 14,
      },
      {
        id: 'id_special-feature_4',
        name: 'special-feature',
        value: 'autumn-interest',
        label: 'Autumn interest',
        count: 22,
      },
      {
        id: 'id_special-feature_5',
        name: 'special-feature',
        value: 'winter-interest',
        label: 'Winter interest',
        count: 23,
      },
      {
        id: 'id_special-feature_6',
        name: 'special-feature',
        value: 'renter-friendly',
        label: 'Renter friendly',
        count: 11,
      },
      {
        id: 'id_special-feature_7',
        name: 'special-feature',
        value: 'variegated-patterned',
        label: 'Variegated & patterned',
        count: 42,
      },
      {
        id: 'id_special-feature_8',
        name: 'special-feature',
        value: 'rare-unusual',
        label: 'Rare & unusual',
        count: 10,
      },
      {
        id: 'id_special-feature_9',
        name: 'special-feature',
        value: 'edible',
        label: 'Edible',
        count: 10,
      },
      {
        id: 'id_special-feature_10',
        name: 'special-feature',
        value: 'colourful',
        label: 'Colourful',
        count: 21,
      },
      {
        id: 'id_special-feature_11',
        name: 'special-feature',
        value: 'peat-free',
        label: 'Peat free',
        count: 17,
      },
    ],
  },
  {
    title: 'Plant type',
    filters: [
      {
        id: 'id_plant-type_0',
        name: 'plant-type',
        value: 'flowering',
        label: 'Flowering',
        count: 30,
      },
      {
        id: 'id_plant-type_1',
        name: 'plant-type',
        value: 'ferns',
        label: 'Ferns',
        count: 11,
      },
      {
        id: 'id_plant-type_2',
        name: 'plant-type',
        value: 'cacti-succulents',
        label: 'Cacti & succulents',
        count: 9,
      },
      {
        id: 'id_plant-type_3',
        name: 'plant-type',
        value: 'palms',
        label: 'Palms & trees',
        count: 20,
      },
      {
        id: 'id_plant-type_4',
        name: 'plant-type',
        value: 'hanging-plants',
        label: 'Hanging & climbing',
        count: 19,
      },
      {
        id: 'id_plant-type_5',
        name: 'plant-type',
        value: 'edibles',
        label: 'Edibles',
        count: 12,
      },
      {
        id: 'id_plant-type_6',
        name: 'plant-type',
        value: 'bamboo-grasses',
        label: 'Bamboo & grasses',
        count: 3,
      },
    ],
  },
  {
    title: 'Style',
    filters: [
      {
        id: 'id_style_0',
        name: 'style',
        value: 'cottage',
        label: 'Cottage',
        count: 12,
      },
      {
        id: 'id_style_1',
        name: 'style',
        value: 'jungle',
        label: 'Jungle',
        count: 10,
      },
      {
        id: 'id_style_2',
        name: 'style',
        value: 'mediterranean',
        label: 'Mediterranean',
        count: 10,
      },
      {
        id: 'id_style_3',
        name: 'style',
        value: 'colourful',
        label: 'Colourful',
        count: 13,
      },
      {
        id: 'id_style_4',
        name: 'style',
        value: 'japanese',
        label: 'Japanese',
        count: 13,
      },
      {
        id: 'id_style_5',
        name: 'style',
        value: 'modern',
        label: 'Modern',
        count: 19,
      },
    ],
  },
  {
    title: 'Plant height',
    filters: [
      {
        id: 'id_plant-height_0',
        name: 'plant-height',
        value: 'tall',
        label: 'Tall / 1m-2.8m',
        count: 31,
      },
      {
        id: 'id_plant-height_1',
        name: 'plant-height',
        value: 'medium',
        label: 'Medium / 50cm-1m',
        count: 53,
      },
      {
        id: 'id_plant-height_2',
        name: 'plant-height',
        value: 'small',
        label: 'Small / 15-50cm',
        count: 84,
      },
      {
        id: 'id_plant-height_3',
        name: 'plant-height',
        value: 'tiny',
        label: 'Tiny / 0-15cm',
        count: 6,
      },
    ],
  },
];